### ISSUE TITLE
webRTC拉流没有声音，只有画面，需要怎么处理？

### ISSUE THREAD

**Issue by choui666** [zegodev/webrtcDemo-js#17]

**Comment by zegodev** [comment]
目前已知有一种情况会这样：在safari上，如果加载后自动播放视频流，默认是没有声音的，需要用户与页面交互后才会正常播放；这个是safari浏览器自动播放策略，用户可以手动更改该策略；经验证，如果在播放之前调用过摄像头，也是可以算作与页面交互过；开发人员可以针对这个策略做下合适的处理；
