### ISSUE TITLE
webRTC只推音频不推视频流，需要怎么实现？

### ISSUE THREAD

**Issue by choui666** [zegodev/webrtcDemo-js#2]

**Comment by zegodev** [comment]
- 预览不启用video或者audio就可以实现单推音频和视频
- 拉流播放可以在调用startPlayingStream(streamid, remoteVideo, audioOutput,playOption) 时，在最后一个参数playOption传入以下值：
{playType:'video'} ---播放纯视频
{playType:'audio'}---播放纯音频
{playType:'all'}---播放音视频

例：startPlayingStream(123, remoteVideo, audioOutput,{playType:'audio'})
