### ISSUE TITLE
windows系统firefox 怎么激活OpenH264 视频编码器插件？

### ISSUE THREAD

**Issue by choui666** [zegodev/webrtcDemo-js#23]

**Comment by zegodev** [comment]
许多视频流媒体依靠 H.264 解码器工作。由于许可限制，H.264 不能在开源软件，如 Firefox 上使用。Firefox 使用了其开源替代品， OpenH264 来支持视频通话功能。

思科系统公司与 Mozilla 合作发布了 OpenH264。它随 Firefox 自动安装，以支持与需要 H.264 解码器的设备间的视频通话功能。

正常情况下是默认激活的，若因为某种原因关闭了，可在火狐浏览器地址栏输入about:addons-->插件，激活
