### ISSUE TITLE
safari 用 360*240 的分辨率 推流 出现 花屏的情况，要怎么解决？

### ISSUE THREAD

**Issue by ZegoPaul** [zegodev/webrtcDemo-js#28]
Safari 推流 分辨率在 320*240 会出现花屏的情况，用chrome和foxfire 都没有问题，这是什么原因？需要这么解决呢？

**Comment by choui666** [comment]
自定义分辨率在不同浏览器中表现不一样，推荐大家用官网定义的几种分辨率
