### ISSUE TITLE
无法获取设备信息browser don't support enumerate devices；chrome最新版

### ISSUE THREAD

**Issue by wuweikd** [zegodev/webrtcDemo-js#37]
![image](https://user-images.githubusercontent.com/34428646/64508959-4d855800-d311-11e9-8d24-727f90f577c2.png)

提示websocket失败
![image](https://user-images.githubusercontent.com/34428646/64509331-13688600-d312-11e9-8f5e-724af9c00bf0.png)

**Comment by BansheeHannibal** [comment]
是否是在http协议下运行的？webRTC 目前只支持localhost 与 https

**Comment by wuweikd** [comment]
> 是否是在http协议下运行的？webRTC 目前只支持localhost 与 https

对！
