### ISSUE TITLE
webRTC从CDN拉流怎么实现？

### ISSUE THREAD

**Issue by choui666** [zegodev/webrtcDemo-js#5]

**Comment by zegodev** [comment]
- 获取cdn拉流地址，在调用s d k登录后，会返回所有房间内拉流c d n地址
- 播放c d n地址；目前sdk会返回3种协议头视频地址：flv,m3u8,rtmp;

 flv格式是首选播放格式，延迟低，兼容性高（除iphone外，主流现代浏览器基本都支持）
 m3u8是ios独有，延迟比flv稍高，时候在iphone上使用
 rtmp需要使用flash插件
（以上是建议，开发者可结合自己情况选择）
